#!/usr/bin/env ruby
require_relative './services/auction/base_service'
require_relative './services/auction/english'
require_relative './services/auction/users'
require_relative './services/auction/highest_bid'
Auction::English.new.call