# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rspec', '~> 3.9', group: :test

gem 'rubocop', '~> 0.89.1'

group :development do
  gem 'guard'
  gem 'guard-rspec', require: false
end
